### ISSUE TITLE
ng test my-app app.component.ts => Unknown option: 'app.component.spec.ts'

### ISSUE THREAD

**Issue by mseknibilel** [meltedspark/angular-builders#130] opened 2018-10-29 05:58 UTC
The builder is not passing the test pattern to jest

'C:\Program Files\nodejs\node.exe' '--inspect-brk=34963' 'node_modules\@angular\cli\bin\ng' 'test' 'client-app' **'app.component.spec.ts'** '--testNamePattern' 'should render title in a h1 tag'
Debugger attached.
**Unknown option: 'app.component.spec.ts**'

**To Reproduce**
1. Go to 'https://github.com/mseknibilel/ng-jest-vscode-demo'
2. Clone repo and install jest extension 
3. Go to '/projects/client-app/src/app/components/app/app.component.spec.ts'
4. click on a debug above the failing tests
5- look at the output of the terminal tab in vscode

![image](https://user-images.githubusercontent.com/1716566/47631864-10c0d000-db48-11e8-8fa3-a078f36d634a.png)

**Comment by mseknibilel** [comment] 2018-10-29 07:41
the command line is automatically executed by the Jest extension so i can't modify it.
In addition, according to [jest docs](https://jestjs.io/docs/en/cli#running-from-the-command-line)

the syntax is correct:
![image](https://user-images.githubusercontent.com/1716566/47635779-7ae07180-db56-11e8-9e43-3bb5ee4170b3.png)

**Comment by meltedspark** [comment] 2018-10-29 07:52
I see... The problem is that you're trying to use Jest extension with `ng test` and not `jest`. These are not the same therefore the problem.  
I'll see what can be done, meanwhile you can try [this](https://github.com/meltedspark/angular-builders/issues/25#issuecomment-430666875) as a solution for debug.

**Comment by mseknibilel** [comment] 2018-10-29 08:11
Thanks @meltedspark , btw, it was working well with CLI 6 but broke after updating to the CLI 7
The Jest extension is pretty handy and i believe that the builder should be compatible

**Comment by meltedspark** [comment] 2018-10-29 08:48
@mseknibilel Yeah, they fixed schema matching in Angular CLI 7, so it won't recognize any unspecified options (which `app.component.ts` is). It might be difficult to overcome this constraint but I'll take a look. 
Let me know if you managed to debug without Jest extension.

**Comment by meltedspark** [comment] 2018-11-02 18:21
Ok, here are the results of the investigation.
1. It never worked before (the `app.component.spec.ts` part). What did work is the `testNamePattern` part.  
That means if you have two different test suites with the same test name - both tests will run although you only invoked one of them with this Jest extension.
2. Any option that is provided to `ng run` (or any known shortcut such as `ng test`, `ng build`) without 
`--` prefix considered an _Angular CLI option_.  Since `app.component.spec.ts` is not a known Angular CLI option you get this error.  
You can check out the parser function implementation [here](https://github.com/angular/angular-cli/blob/2bb26f197b9709f9608be7f6f3ba64a43efab9ce/packages/angular/cli/models/parser.ts#L261), and [here](https://github.com/angular/angular-cli/blob/2bb26f197b9709f9608be7f6f3ba64a43efab9ce/packages/angular/cli/models/architect-command.ts#L146) is the error source.
3. If you do find a way to provide this option with dashes (like `--app.component.spec.ts`) it will pass the validation against Angular CLI options schema, but will still fail on a validation against the builder schema.  
To make it pass you have to explicitly add property `app.component.spec.ts` to the properties array of the [builder schema](https://github.com/meltedspark/angular-builders/blob/master/packages/jest/src/schema.json), which of course does not make any sense.  
It would have worked if the Angular team treated properly `additionalProperties` in schema validation, but currently they don't.

The conclusion is that unfortunately there is no way (for now) to overcome this limitation.

What can be done:
1. [Debugging the test](https://github.com/meltedspark/angular-builders/issues/25#issuecomment-430666875) without Jest extension.
2. Finding a way to get rid of `app.component.spec.ts` in command line while using Jest extension (instead add a suite name inside `testNamePattern`).
3. Writing your own extension (I believe it is pretty easy to fork the Jest extension and modify it so that it supports Angular CLI).

These are my conclusions, and I'm open for suggestions, but currently I'm closing this issue as there is nothing to do with that on my side.

**Closed by meltedspark** 2018-11-02 18:21 UTC
Labels: builders:jest, workaround-provided

**Comment by mseknibilel** [comment] 2018-11-05 07:37
Thanks for the explanation ! Eventually i might go with the forking of the extension or may be create mine :)

**Comment by meltedspark** [comment] 2018-11-05 10:03
Sure, keep me posted.

**Comment by michaeljota** [comment] 2021-03-08 16:13
Hi. I'm thinking about this, and, what if this allows a `--file` option to be passed. This `file` or `files` IDK, would be passed to jest without the argument option because Jest would know that is getting a file name. This could fix the issue with the Jest VSCode extension when debugging.
