### ISSUE TITLE
Jest global config not being used

### ISSUE THREAD

**Issue by mcblum** [meltedspark/angular-builders#202] opened 2019-01-18 15:37 UTC
**Describe the bug**
Global definitions for `ts-jest` in the `jest.config.js` file seem to be ignored.

**To Reproduce**
1. We're using Nx, so we've got a structure where all of our features are in `/libs/{name}`. 
2. I've specified all of the configuration required in the `angular.json` file, and running tests for specific libs is working.
3. Each time a test suite is run, we get a series of errors that look like:
```
ts-jest[backports] (WARN) "[jest-config].globals.__TRANSFORM_HTML__" is deprecated, use "[jest-config].globals.ts-jest.stringifyContentPathRegex" instead.
ts-jest[backports] (WARN) "[jest-config].globals.ts-jest.tsConfigFile" is deprecated, use "[jest-config].globals.ts-jest.tsConfig" instead.
ts-jest[backports] (WARN) Your Jest configuration is outdated. Use the CLI to help migrating it: ts-jest config:migrate <config-file>.
ts-jest[backports] (WARN) "[jest-config].globals.ts-jest.tsConfigFile" is deprecated, use "[jest-config].globals.ts-jest.tsConfig" instead.
ts-jest[backports] (WARN) Your Jest configuration is outdated. Use the CLI to help migrating it: ts-jest config:migrate <config-file>.
ts-jest[backports] (WARN) "[jest-config].globals.__TRANSFORM_HTML__" is deprecated, use "[jest-config].globals.ts-jest.stringifyContentPathRegex" instead.
``` 
This used to happen to us before we upgraded our version of `angular-preset-jest` and is related to the old default config. The new config style should be:

```
globals: {
        'ts-jest': {
            tsConfig: '<rootDir>/tsconfig.spec.json',
            diagnostics: false,
            stringifyContentPathRegex: '\\.html$',
            astTransformers: [
                'jest-preset-angular/InlineHtmlStripStylesTransformer.js'
            ]
        },
        window: true
    },
```
which we have inside of `jest.config.js` which is located at the root of our project.
4. My understanding based on the readme is that it uses this base config and the merged and overridden props in the individual `jest.config.js` files on top, but that doesn't seem to be happening.

**Expected behavior**
It should use the base config and then combine properties from the files located within the libraries.

**Libraries**
"@angular-devkit/build-angular": "~0.10.0",

**Additional context**
Thank you!

**Comment by meltedspark** [comment] 2019-01-18 19:01
Hi, indeed, according to the [docs](https://github.com/meltedspark/angular-builders/tree/master/packages/jest#builder-options) (as well as to implementation) the builder should add on top of each project the configuration specified in _angular.json_ or in _jest.config.js_ located in the root of the workspace. If it is not happening that is definitely a bug.  


Anyways, in terms of `angular-preset-jest`, you're not supposed to install it yourself, the builder does it for you and the builder version depends on a very specific version of the preset.  
If you're interested in using the newest version of the preset (which uses the configuration you described) you should use the corresponding version of the builder (which would be `7.3.0-alpha.1`). You can install it with `yarn add -D @angular-builders/jest@jest-preset-alpha`.  

In any case (even if using the alpha version helps you with your issue), I'd appreciate if you created a minimal reproduction repository for this bug so that I could isolate the root cause.

**Comment by mcblum** [comment] 2019-01-21 15:36
@meltedspark yes! Awesome, that was totally it. The issue was in fact that we are basically migrating from our own install of jest and a single config for the entire monorepo to individualized configs for each feature folder. Because the version of `jest-preset-angular` that ships with the builder is older than the version we were running, the updated config we were using was basically being ignored or something.

I'll try to figure out how to reproduce this but I *think* it would just be using a base config meant for the older version of `jest-preset-angular` with the alpha version that expected different options.

**Comment by meltedspark** [comment] 2019-01-21 15:43
Yeah, but regardless of `jest-preset-angular` version the global config should have been overriding the default one, so if it wasn't working it is a problem...

**Comment by meltedspark** [comment] 2019-01-28 15:52
Hey @mcblum, any success on reproducing the bug or I should close the issue?

**Closed** 2019-04-30 10:30 UTC
Labels: builders:jest
