### ISSUE TITLE
Example project's tests can't be run with intellij

### ISSUE THREAD

**Issue by sroettering** [meltedspark/angular-builders#203] opened 2019-01-22 16:49 UTC
**Describe the bug**
I cloned the examples folder of the jest builder and tried to run the `multiple-apps` example directly from intellij and it didn't work. The first app (`my-first-app`) runs correctly. The second one (`my-second-app`) uses a `testMatch` option which searches test files in `my-first-app` and when running `my-shared-library` tests the rootDir is set to the lib root.
Running the tests via `ng test <project-name>` from a terminal works fine, however.

This could be either a configuration issue within the example app or with intellij passing the wrong parameters.
Maybe @segrey can have a look at the intellij side.

**To Reproduce**
1. Clone and open the multiple-apps example with intellij
2. Do an npm or yarn install
3. Execute a test case in each of the three projects directly from intellij (the little play button)

**Expected behavior**
Each test case should be executable within intellij

**Builder:**
 - jest-builder
 - v7.2.1

**Comment by meltedspark** [comment] 2019-01-23 21:55
There are two issues actually. When I run a test from _my-second-app_ the `testMatch` in the resulting config is still for _my-first-app_.  
That requires investigation, my guess is that it has something to do with the way IntelliJ runs `ng test`. It runs it without the project parameter (`ng test` and not `ng test my-second-app`) so the default app is taken as a project. The builder sets `testMatch` according to the project it is running with, i.e.  _my-first-app_. But again, that's a guess.  
When I run the lib project though, the problem is completely different - the `<rootDir>` is set to _my-shared-library_ folder. That happens because the working directory (in Jest run configuration) is being set to _my-shared-library_, while for the apps it is being set to the root of the workspace (_multiple-apps_).  
I don't know why IntelliJ treats projects and libs differently, probably @segrey can shed some light on that.  

In any case, I think that once the second problem is solved it will behave the same way _my-second-app_ behaves, for the reasons I mentioned above. I still have to check that I'm correct about by clues, but if I am, IntelliJ has to call `ng test` with the project parameter in order to make it work.

**Comment by sroettering** [comment] 2019-01-30 09:14
Any news on this?

**Comment by meltedspark** [comment] 2019-01-30 15:48
@segrey Cool! As far as I understand the first has been fixed already, any idea when it will be rolled out?  

As for the second... I think the IntelliJ should choose the right directory without forcing the user to manually set it via configuration. What about fallback? Try to run with lib directory as workspace directory and if errored try the next parent directory.  
I guess that would be a very common problem because it will happen in every library project in Angular. So it has to be dealt with.

Regarding running `ng test my-project` from within the project directory... I'm not sure I understand the use case. Could you elaborate on what you mean?

And thanks for the cooperation, appreciate that very much!

**Comment by segrey** [comment] 2019-01-30 17:52
The fix for WEB-37031 will be available in WebStorm 2019.1 EAP (build > 191.4900), it will be uploaded the next week (https://www.jetbrains.com/webstorm/eap/).

>the IntelliJ should choose the right directory without forcing the user to manually set it via configuration

Now `ng test` should be run from the root directory for `@angular-builders/jest`. However, running from the root directory might not work for some other projects. For example, a module in a multi-module project may configure its Jest tests in some special way, via "jest" property in module's package.json or jest.config.js file. Running Jest tests from the root directory won't pickup these configurations. Please see https://youtrack.jetbrains.com/issue/WEB-31201 and https://youtrack.jetbrains.com/issue/WEB-31305 for details.
Well, current logic for calculating working directory is just a heuristics and it may fail for some other projects, that's true. In this case, "Working directory" can be set in UI.
Maybe it's possible to improve the calculation logic somehow without breaking WEB-31201/WEB-31305. How about using the closest ancestor package.json with "jest" property?

>What about fallback? Try to run with lib directory as workspace directory and if errored try the next parent directory.

Tests will run longer and with unclear side effects. Also, it's not clear what "error" means here, because a test may fail, because of failed assertion. I'd rather not go this way ;)

>I guess that would be a very common problem because it will happen in every library project in Angular.

BTW, it doesn't happen if Karma test runner is used: `ng test <project-name>` command can be run successfully from both the root (`my-angular-app/`) and project directory (`my-angular-app/projects/app-two`). It works for me with default Angular CLI generated project.
Is it possible to support same behavior for Jest test runner? Why `ng test <project-name>` should be run from the root directory only? (That's what I meant by "`ng test my-project` from within the project directory").

**Comment by meltedspark** [comment] 2019-02-01 19:41
Fixed in `7.2.2`

**Closed** 2019-02-01 19:49 UTC
Labels: bug, builders:jest

**Comment by meltedspark** [comment] 2019-02-01 21:01
Fixed in `7.2.3`
