### ISSUE TITLE
Custom postcss plugins won't work in production build

### ISSUE THREAD

**Issue by mihaliak** [meltedspark/angular-builders#66] opened 2018-09-18 09:45 UTC
Hey,

I am trying to use postcss with tailwindcss plugin. It works for `ng serve` and `ng build` but when using `ng build --prod` to build production assets, it doesnt run tailwindcss plugin. I added console log at start of custom webpack file, it shows in console but it just doesnt run tailwindcss plugin.

My custom webpack looks like this:

```js
const tailwindcss = require('tailwindcss');

console.log('** Custom webpack config was loaded.');

module.exports = {
    module: {
        rules: [
            {
                test: /\.css$/,
                use: [
                    {
                        "loader": "postcss-loader",
                        "options": {
                            "ident": "embedded",
                            "plugins": [
                                tailwindcss('./tailwind.js'),
                            ],
                            "sourceMap": true
                        }
                    }
                ]
            },
        ],
    },
};
```

I have tried all mergeStrategies in angular.json configuration but it doesnt work anyway.

**Comment by meltedspark** [comment] 2018-09-18 11:01
If you add a print at the beginning of `tailwind.js` file, does it show up in the log? Both in prod and dev build?  
Do you use `dev-server:generic` for `ng serve` target?  
What happens if you run `ng serve` in production mode?

**Comment by mihaliak** [comment] 2018-09-18 11:14
I added print at the beginning of tailwind.js file and it shows up **only** in dev build.

Yes I am using `@angular-builders/dev-server:generic` for `ng serve`.

If I run `ng serve --prod` it doesnt work aswell. Only `ng serve` (dev) works.

It logs "Custom webpack config was loaded" but not log from tailwind.js which means its not running postcss  tailwind plugin.

**Comment by mihaliak** [comment] 2018-09-24 10:02
Any update about this?

**Comment by meltedspark** [comment] 2018-09-25 21:20
Funny thing - I took a look at their internals and I'm very surprised that the behavior is inconsistent. To be precise, I'd say it shouldn't work neither in dev build nor in production.  
You see, `postcss-loader` [can receive](https://github.com/postcss/postcss-loader#plugins) either Array or Function (that returns an array) as `plugins` value.  
You can see that in their [implementation](https://github.com/angular/angular-cli/blob/3529096a5398526f97f0c4ace76e48bbf50431fd/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts) (that is relevant for Angular CLI 6) they are using the second option - Function. You are overriding this entry with an array, basically disabling all the functionality they define. This is not very good, I believe your intention was to add on top of this functionality  instead of replacing that completely.  
In any case I don't understand what is the difference here between dev build and production so a repository with minimal reproduction would be really helpful.  
But even when we find the root cause and fix it you'll have to take [this](https://github.com/angular/angular-cli/blob/3529096a5398526f97f0c4ace76e48bbf50431fd/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts#L66) array as a base line for your `plugins` array in `postcss-loader` options.

**Comment by mihaliak** [comment] 2018-09-26 09:37
Thanks for checking it out. I made repository with simple tailwind page.

[mihaliak/angular-builders-bug](https://github.com/mihaliak/angular-builders-bug)

I added screenshot.png to repository, in screenshot you can see success tailwind build (dev serve or build).

Can you check it please and if possible fix it ? Copying array as base line for my plugins in postcss-loader wont be problem I think, is there any es6 version of this array? Or have idea how to use ts version in custom webpack config?

Thanks!

**Comment by meltedspark** [comment] 2018-09-29 09:40
Ok, so a few good news and a few bad. 
**_The good:_**

1. You don't have to dig through their configuration to align with it - the plugin creator function is applied before it comes to the merge.
2. The merge works just as expected (the extra configuration is being merged in both product and development modes). It's a bit strange it doesn't merge the `\\/.css$` rule but it doesn't affect the configuration.

**_The bad:_**

I still don't know why `tailwind.js` file is not loaded in production mode.  
I've serialized [runtime configurations](https://github.com/meltedspark/angular-builders-bug/tree/master/bug-investigation/runtime-configs) so that you can easily diff between production and development merged configs.  
I'd say it's is not a bug in `angular-builders/custom-webpack` but rather a configuration issue (for production it probably should be configured in a different way).  
Most probably that the problem is related to the fact that in production build they use `mini-css-extract-plugin` instead of `style-loader` or their own version of `raw-loader` (`@angular-devkit\\build-angular\\src\\angular-cli-files\\plugins\\raw-css-loader.js`) instead of plain `raw-loader`.  
I will continue the investigation but in a meantime you can play with the configuration a bit and try to figure out what is the exact source of the problem.

**Comment by mihaliak** [comment] 2018-10-12 08:54
Hello,

any new info about this? This is not related only to tailwind but any postcss plugins.

Thanks

**Comment by meltedspark** [comment] 2018-10-19 13:07
No news yet, I do believe it is an issue with configuration and not with the builder.  
Have to investigate in depth how `mini-css-extract-plugin` affects the situation.

**Comment by mihaliak** [comment] 2018-12-05 08:57
Setting `extractCss` to `false` in angular.json file fixed this issue, extra webpack config is loaded and build is ok.

**Closed** 2018-12-05 12:02 UTC
Labels: builders:custom-webpack, not-an-issue, question
