### ISSUE TITLE
Problem on Angular 8

### ISSUE THREAD

**Issue by abadakhshan** [meltedspark/angular-builders#324] opened 2019-05-29 09:28 UTC
**Describe the bug**
After upgrade to angular & angular CLI  8
on "ng serve" I get this error :

"Could not find the implementation for builder @angular-builders/dev-server:generic"

I use  

"@angular-builders/custom-webpack": "^7.4.3",
 "@angular-builders/dev-server": "^7.3.1"

**Comment by meltedspark** [comment] 2019-05-29 09:29
Duplicate of #323

**Closed by meltedspark** 2019-05-29 09:29 UTC

**Comment by meltedspark** [comment] 2019-05-29 10:11
`@angular-builders/dev-server` has been deprecated in `8.0.0`. Please read the [migration guide](https://github.com/meltedspark/angular-builders/blob/master/MIGRATION.MD).

**Comment by abadakhshan** [comment] 2019-05-29 10:21
My problem was solved

Thank you  @meltedspark

**Comment by jsasw** [comment] 2019-07-25 10:01
Hello to All.
Strangely i had the same problem while trying to use custom builders for environment variables.
I runned  **ng build**  and then 
when i runned **ng serve** it start working

**Comment by szhang6** [comment] 2020-02-17 04:12
> Hello to All.
> Strangely i had the same problem while trying to use custom builders for environment variables.
> I runned **ng build** and then
> when i runned **ng serve** it start working



> Hello to All.
> Strangely i had the same problem while trying to use custom builders for environment variables.
> I runned **ng build** and then
> when i runned **ng serve** it start working

Strangely, I have tried run "**ng build"** and then run '**ng serve**', while still hit the same issue.

**Comment by szhang6** [comment] 2020-02-17 06:08
> My problem was solved
> 
> Thank you @meltedspark

Hi Bro, I hit the same issue, could you kindly explain how did you solve this issue?

**Comment by exequielc** [comment] 2021-09-10 11:59
Got the same bug can you exaplain how did you solve?? @szhang6 @abadakhshan

**Comment by abadakhshan** [comment] 2021-09-10 13:58
> Got the same bug can you explain how did you solve?? @szhang6 @abadakhshan

@angular-builders/dev-server:generic is deprecated. You should use `@angular-builders/custom-webpack` and `@angular-builders/custom-webpack:dev-server`

You could find a sample [here](https://github.com/NarikMe/narik-micro-frontends-sample/blob/master/angular.json)
