### ISSUE TITLE
Cannot read property 'baseHref' of undefined

### ISSUE THREAD

**Issue by seiyria** [meltedspark/angular-builders#196] opened 2019-01-09 22:23 UTC
**Describe the bug**

When using ng serve, I get this:

```
Cannot read property 'baseHref' of undefined
TypeError: Cannot read property 'baseHref' of undefined
    at GenericDevServerBuilder._buildServePath (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:233:80)
    at GenericDevServerBuilder._buildServerConfig (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:123:32)
    at GenericDevServerBuilder._buildServerConfig (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/@angular-builders/dev-server/src/generic/index.js:11:109)
    at MergeMapSubscriber.check_port_1.checkPort.pipe.operators_1.concatMap [as project] (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:41:47)
    at MergeMapSubscriber._tryNext (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/rxjs/internal/Subscriber.js:67:18)
    at TapSubscriber._next (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/rxjs/internal/operators/tap.js:65:26)
    at TapSubscriber.Subscriber.next (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/rxjs/internal/Subscriber.js:67:18)
    at ForkJoinSubscriber.notifyComplete (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/rxjs/internal/observable/forkJoin.js:82:25)
    at InnerSubscriber._complete (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/rxjs/internal/InnerSubscriber.js:35:21)
    at InnerSubscriber.Subscriber.complete (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/rxjs/internal/Subscriber.js:79:18)
    at MapSubscriber.Subscriber._complete (/Users/seiyria/GitHub/deck-zone-ng7/node_modules/rxjs/internal/Subscriber.js:97:26)
```

**To Reproduce**

https://github.com/seiyria/deck.zone/tree/ng7

npm i && npm start

**Expected behavior**
No error when trying to serve

**Builder:**
 - dev-server:generic & custom-webpack:browser, both at 7.2.0

**Libraries**
 - `angular-devkit/build-angular`: 0.11.0

**Additional context**
None

**Comment by meltedspark** [comment] 2019-01-09 22:35
Please use either `angular-devkit/build-angular@0.12.1` with `@angular-builders/dev-server@7.2.0` or `angular-devkit/build-angular@0.11.0` with `@angular-builders/dev-server@7.1.1`.

**Comment by seiyria** [comment] 2019-01-09 22:59
I did a quick `npm i -D @angular-devkit/build-angular@0.12.1` and tried npm start and got the same error, was I supposed to do anything else to upgrade?

**Comment by meltedspark** [comment] 2019-01-10 07:05
Nope, just checked, the issue exists with `0.12.1` as well. On it.

**Comment by meltedspark** [comment] 2019-01-10 07:06
Just to confirm - everything works with `7.1.1` and `0.11.0`?

**Comment by meltedspark** [comment] 2019-01-10 08:51
Fixed in `7.2.1`

**Closed** 2019-01-10 08:51 UTC
Labels: bug, builders:dev-server

**Comment by yannbf** [comment] 2019-01-10 12:39
@meltedspark I was about to open an issue regarding the same thing. I am using version 7.2.1 and it is still there. I downgraded to 7.1.1 to keep the build working.

**Comment by seiyria** [comment] 2019-01-10 14:35
Cool, 7.2.1 works for me. I did not check the old version since I was done for the day, but thanks for following up!

**Comment by meltedspark** [comment] 2019-01-10 15:30
@yannbf Are you positive it is reproduced with `7.2.1`? Are you able to reproduce it within a clean workspace?

**Comment by yannbf** [comment] 2019-01-11 13:55
@meltedspark `7.2.1` is working indeed! Found out that the problem was that I was using `angular-devkit/build-angular@0.11.0`. Once I upgraded it, it worked fine! Thanks :))

**Comment by amhazeem** [comment] 2019-03-13 09:16
Issue still exists in 7.4.5 alongside devkit 0.7.5

**Comment by meltedspark** [comment] 2019-03-13 10:03
@amhazeem please upgrade your devkit.

**Comment by amhazeem** [comment] 2019-03-13 10:22
Thanks . Its resolved now
